#!/usr/bin/env bash

project_name=AnathemOS

if [ ! -f ~/.bash_aliases ]; then
    touch ~/.bash_aliases
    chmod +x ~/.bash_aliases
fi 

qemu='alias qemu=qemu-system-i386'
if  grep -Fxq "$qemu" ~/.bash_aliases; then
    echo "[$project_name] alias already appended"
    exit 1
fi

echo $qemu>>~/.bash_aliases
source ~/.bashrc

